In [1]:
import numpy as np

In [2]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [3]:
print (v1)
print (v2)

[1 2 3]
[4 5 6]


In [4]:
v_add = v1 + v2
v_sub = v1 - v2

In [5]:
print (v_add)
print (v_sub)

[5 7 9]
[-3 -3 -3]


In [6]:
scalar = 2
v_scaled = scalar * v1

In [7]:
print (v_scaled)

[2 4 6]


In [8]:
dot_product = np.dot(v1, v2)

In [9]:
print (dot_product)

32


In [10]:
magnitude_v1 = np.linalg.norm(v1)
print (magnitude_v1)

3.7416573867739413


In [12]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print()

B = np.array([[7, 8, 9],[10, 11, 12], [13, 14, 15]])
print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [16]:
C = np.array([[1, 2, 3], [4, 5, 6]])
matrix_add = A + C
matrix_sub = A - C

print ("A+C=\n", matrix_add)
print ("A-C=\n", matrix_sub)

A+C=
 [[ 2  4  6]
 [ 8 10 12]]
A-C=
 [[0 0 0]
 [0 0 0]]


In [17]:
matrix_mul = np.dot(A, B)
print(matrix_mul)

[[ 66  72  78]
 [156 171 186]]


In [18]:
transpose_A = A.T
print(transpose_A)

[[1 4]
 [2 5]
 [3 6]]


In [26]:
A = np.array([[2, 3, 0], [4, -1, 0], [1, 1, 0]])

b = np.array([[5, 3, 2]])

print (A)
print (b)
x = np.linalg.solve(A, b)
print ("Solution:")
print(x)

[[ 2  3  0]
 [ 4 -1  0]
 [ 1  1  0]]
[[5 3 2]]


ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 1 is different from 3)

In [28]:
A = np.array([[2, 1], [1, 2]])
e_value, e_vector = np.linalg.eig(A)

In [29]:
print("eigenvalue:", e_value)
print("eigenvector:", e_vector)

eigenvalue: [3. 1.]
eigenvector: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [30]:

A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)

print(A)
print(A_inv)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [31]:
identity = np.dot(A, A_inv)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [32]:
# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
# Perform SVD
U, sigma, Vt = np.linalg.svd(A)
print("U matrix:\n", U)
print("Sigma values:", sigma)
print("V^T matrix:\n", Vt)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma values: [9.52551809 0.51430058]
V^T matrix:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
